num_particles: 1024
robot: fr5
grasp_dof: 4
place_dof: 4
approach: optimization
num_resampling_attempts: 100
num_opt_steps: 1000
lr: 0.007
conf_lr: 0.02226
max_loop_dur: null
break_on_satisfying: true
stick_button_experiment: false
optimize_soft_costs: false
soft_cost: null
num_initial_plans: 1
explored_state_check: true
cache_subgraphs: null
skip_failed_subgraphs: false
random_init: false
coll_n_spheres: 50
coll_sphere_radius: 0.005
world_activation_distance: 0.0
gripper_activation_distance: 0.0
movable_activation_distance: 0.0
enable_traj: false
curobo_plan: true
time_dilation_factor: 0.5
warmup_ik: true
warmup_motion_gen: true
enable_visualizer: true
opt_viz_interval: 10
viz_robot_mesh: true
rr_spawn: true
enable_experiment_logging: true
experiment_root: /home/home/sdl_ws/src/sdl_project/TAMP/cuTAMP/cutamp/cutamp_experiments
